# Generated by Django 4.2.6 on 2023-10-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image_url_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
    ]
