# Generated by Django 4.2.6 on 2023-10-18 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='ETB', max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('payment_title', models.CharField(default='Payment', max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('created', 'CREATED'), ('pending', 'PENDING'), ('success', 'SUCCESS'), ('failed', 'FAILED')], default='created', max_length=50)),
                ('response_dump', models.JSONField(blank=True, default=dict)),
                ('checkout_url', models.URLField(blank=True, null=True)),
                ('tax_ref', models.CharField(default='AstridFrostIce', max_length=50)),
                ('return_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('amole', 'AMOLE'), ('hello_cash', 'HELLO_CASH'), ('telle_birr', 'TELLE_BIRR'), ('chapa', 'CHAPA')], default='chapa', max_length=255)),
                ('attendance_method', models.CharField(choices=[('inperson', 'INPERSON'), ('online', 'ONLINE')], default='inperson', max_length=255)),
                ('is_vip', models.BooleanField(default=False)),
                ('Quantity', models.IntegerField(default=1)),
                ('TotalPrice', models.IntegerField(default=0)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='ticket_qr_codes/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
